<?php

/*
 * This is more or less a factory for MpxApi, but within Drupal Context for variables.
 */
function mpx_api_factory(){
  $api = &drupal_static(__FUNCTION__);

  $construct['hostname'] = media_mpx_variable_get('hostname');
  $construct['basepath'] = media_mpx_variable_get('basepath');
  $construct['mpxid'] = media_mpx_variable_get('mpxid');
  $construct['allfeed'] = media_mpx_variable_get('allfeed');

  // Try and re-use the same API class for all calls.
  if(!isset($api)){
    $api = new MpxApi($construct);
  }
  return $api;
}
