media_mpx.media_mpx_account.*:
  type: config_entity
  label: mpx Account
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    user:
      label: The user configuration entity associated with this account
      type: string
    account:
      label: The URI of the account
      type: uri
    public_id:
      label: The Public ID of the account
      type: string

media_mpx.media_mpx_user.*:
  type: config_entity
  label: 'mpx User'
  mapping:
    id:
      type: string
      label: 'ID'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    uuid:
      type: string

media.source.media_mpx_media:
  type: media_mpx.account_aware
  label: '"Media" media source configuration'

media_mpx.account_aware:
  type: mapping
  mapping:
    source_field:
      type: string
      label: 'Source field'
    account:
      type: string
      label: 'mpx Account entity ID'

field.formatter.settings.media_mpx_video:
  type: mapping
  label: 'mpx media rendered with a player'
  mapping:
    player:
      type: uri
      label: 'mpx Player'
    auto_play:
      type: boolean
      label: 'Auto play'
    play_all:
      type: boolean
      label: 'Play all'
