media_mpx.media_mpx_account.*:
  type: config_entity
  label: mpx Account
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    user:
      label: The user configuration entity associated with this account
      type: string
    account:
      label: The URI of the account
      type: uri

media_mpx.media_mpx_user.*:
  type: config_entity
  label: 'mpx User'
  mapping:
    id:
      type: string
      label: 'ID'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    uuid:
      type: string
